- name: Install Helm
  shell: "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
  args:
    warn: no

- name: Add the repo "stable"
  shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: Update Helm repo
  shell: helm repo update
